# HW.3-8, 3-9, 3-10
print("# 3-8")
locations = ['hawaii', 'canada', 'japan', 'mexico', 'australia']
print(f"Original list:\n{locations}")
print(f"\nAlphabetically sorted list:")
locations_sorted_asc = sorted(locations)
print(locations_sorted_asc)
print(f"\nOriginal list:\n{locations}")
print(f"\nReverse Alphabetically sorted list:")
locations_sorted_desc = sorted(locations, reverse=True)
print(locations_sorted_desc)
print(f"\nOriginal list:\n{locations}")
print(f"\nReversing the list:")
locations.reverse()
print(locations)
print(f"\nOriginal list:\n{locations}")
print(f"\nSorting the list alphabetically using sort():")
locations.sort()
print(locations)
print(f"\nSorting the list in descending order:")
locations.sort(reverse=True)
print(locations)
print("==========================================================")
print("# 3-9")
guests = ['karen', 'joshua', 'angela', 'andrew', 'pam']
number_of_guests = len(guests)
print(f"I'm inviting {number_of_guests} people to dinner.")
print("==========================================================")
print("# 3-10")
